export const config = {
  serverUrl: process.env.SERVER_URL || 'ws://localhost:2567',
  authUrl: process.env.AUTH_URL || 'http://localhost:2567/api/auth',
  gameVersion: '1.0.0',
  resourceUrl: process.env.RESOURCE_URL || '/assets',
  debug: process.env.NODE_ENV !== 'production',

  camera: {
    defaultDistance: 5,
    defaultHeight: 2,
    minDistance: 2,
    maxDistance: 12,
    sensitivity: 0.15,
    zoomSpeed: 2,
    pitchLimit: 80,
    collisionRadius: 0.3,
  },

  controls: {
    moveForward: 'KeyW',
    moveBackward: 'KeyS',
    moveLeft: 'KeyA',
    moveRight: 'KeyD',
    sprint: 'ShiftLeft',
    jump: 'Space',
    interact: 'KeyF',
    inventory: 'KeyI',
    character: 'KeyC',
    skillPanel: 'KeyK',
    questPanel: 'KeyL',
    partyPanel: 'KeyP',
    mount: 'KeyR',
    skill1: 'Digit1',
    skill2: 'Digit2',
    skill3: 'Digit3',
    skill4: 'Digit4',
    skill5: 'Digit5',
    skill6: 'Digit6',
    skill7: 'Digit7',
    skill8: 'Digit8',
    skill9: 'Digit9',
    skill0: 'Digit0',
  },

  ui: {
    resolution: { width: 1920, height: 1080 },
    fontSize: { small: 14, normal: 16, large: 24, xlarge: 36 },
    colors: {
      health: '#e74c3c',
      mana: '#3498db',
      xp: '#2ecc71',
      gold: '#f1c40f',
      normal: '#ffffff',
      rare: '#3498db',
      epic: '#9b59b6',
      legendary: '#f39c12',
    },
  },
};
